### PR TITLE
Feat: Create personal folder, Seoktae

### PR DESCRIPTION
**Pull request by sansiuchicom**
### Summary
Seoktae folder and the following folders / files were created

### How to Review?
Please check foldering rules

### Estimated time for review
5 min

--------------------
### More info
**PR type**
- [ ] Add feature
- [ ] Delete feature
- [ ] Fix bug
- [ ] Update code for dependencies, environments, builds, etc.
- [x] Else

**Branches**
origin/seoktae

**Test results**
Every file must work fine with no issues

### CODE REVIEW

**Comment by BaikJoonwoo** [comment]
hello seoktae

**Review by SNU-CEE — APPROVED** [review]
good job seoktae good job seoktae
좋습니다 좋습니다!!!!!!!
와우 와우
오케이!!!!!!!!!!!!

**Comment by Jaeminiman** [comment]
Wow~~~~~~

**Review by Jaeminiman — APPROVED** [review]
i approve

**Review by BaikJoonwoo — COMMENTED** [review]
REJECTED

**Pull request merged**
