### PR TITLE
feat: create personal folder - 하이

### PR DESCRIPTION
**Pull request by BaikJoonwoo**
### Summary
하이 folder and the following folders / files were created

### How to Review?
Please check foldering rules

### Estimated time for review
< 5 min

--------------------
### More info
**PR type**
- [x] Add feature
- [ ] Delete feature
- [ ] Fix bug
- [ ] Update code for dependencies, environments, builds, etc.
- [ ] Else

**Branches**
origin/joonwoo

**Test results**
Every file must work fine with no issues

### CODE REVIEW

**Review by SNU-CEE — CHANGES_REQUESTED** [review]
규칙을 지켜주세요!!!

**Comment by Jaeminiman** [comment]
내가 왜?

**Review by sansiuchicom — APPROVED** [review]
At ease!

**Review by SNU-CEE — APPROVED** [review]
Good Job!!!

**Pull request merged**
